#! /usr/bin/awk

BEGIN {
  print "# Generated by create-keycodes.awk from usb_hid_keys.h by MightyPork"
  print "# found at https://gist.github.com/MightyPork/6da26e382a7ad91b5496ee55fdc73db2"
  print 
} 

/^#define KEY_/ {
  print $2 "=" $3
} 

END {
}

