[[protocols]]
name = "trekstor"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
# 0x00 = "KEY_AB"
0x00 = "KEY_AGAIN"
0x01 = "KEY_BRIGHTNESSDOWN"
0x03 = "KEY_5"
0x04 = "KEY_POWER"
0x05 = "KEY_RIGHT"
0x06 = "KEY_ENTER"
0x09 = "KEY_6"
0x0a = "KEY_BACK"
0x0c = "KEY_LEFT"
0x0e = "KEY_AUDIO"
0x0f = "KEY_SUBTITLE"
# 0x10 = "KEY_MEDIA_REPEAT"
0x10 = "KEY_R"
0x12 = "KEY_3"
0x17 = "KEY_2"
0x18 = "KEY_VOLUMEUP"
0x19 = "KEY_9"
0x1a = "KEY_MUTE"
0x1c = "KEY_7"
# 0x1e = "KEY_STOP"
0x1e = "KEY_STOPCD"
0x31 = "KEY_0"
0x32 = "KEY_8"
# 0x33 = "KEY_SHUFFLE"
0x33 = "KEY_S"
0x41 = "KEY_VOLUMEDOWN"
0x45 = "KEY_1"
0x48 = "KEY_BRIGHTNESSUP"
0x4b = "KEY_CHANNELUP"
0x4c = "KEY_PLAYPAUSE"
0x4d = "KEY_DOWN"
0x4e = "KEY_UP"
0x4f = "KEY_4"
# 0x50 = "KEY_FASTFORWARD"
0x50 = "KEY_NEXTSONG"
# 0x58 = "KEY_REWIND"
0x58 = "KEY_PREVIOUSSONG"
0x5a = "KEY_INFO"
0x5b = "KEY_HOME"
0x5c = "KEY_CHANNELDOWN"

